$(document).ready(function(){function o(a,b,c){function e(){g(d.j,d.b);$("caption",h).html(o.g[d.b]+" "+d.j);c(d)}function g(r,j){var p=(new Date(r,j,1)).getDay(),k=o.h[j],i=$("tbody",h).empty(),s=1,u=0,v=$("<tr>");j==1&&(r%4==0&&r%100!=0||r%400==0)&&(k=29);for(i.append(v);s<=k;){for(var z=0;z<=6;z++){var A=$("<td>");v.append(A);if(s<=k&&(u>0||z>=p)){var B=' class="s ';if(f.getMonth()==j&&f.getFullYear()==r&&f.getDate()==s)B+=" today";A.append($("<a"+B+'">'+s++ +"</a>").data("date",new Date(r+"/"+
(j+1)+"/"+(s-1))))}}v=$("<tr>");i.append(v);u++}}var f=new Date;a=isNaN(a)||a==null?f.getMonth():a;b=isNaN(b)||b==null?f.getFullYear():b;var d=this;d.b=a;d.j=b;for(var l='<table class="cal"><caption>'+o.g[a]+" "+b+'<thead><tr><th colspan="7"><tr>',m=0;m<=6;m++)l+="<th>"+o.q[m];l+="<tbody>";var h=$(l);l=$("<span>&#8667;</span>").click(function(){d.b++;if(d.b==12){d.b=0;d.j++}e()});m=$("<span>&#8666;</span>").click(function(){d.b--;if(d.b==-1){d.b=11;d.j--}e()});$("th:first",h).append(m).append(l);
g(b,a);this.a=h;c(d)}function C(a,b){function c(){d.empty();e();new D(d);d.submit(function(){var j=new n(a);$(":input",d).each(function(p,k){var i=$(k),s=i.attr("name"),u=i.val();j[s]=u;i.val("")});j.save();location.reload(true);return false})}function e(j){for(var p=0;p<r.length;p++){var k=r[p],i=k.name.replace("_"," ");d.append("<label>"+i+"</label>");d.append(k.a());j&&l.append("<th>"+i)}d.append('<input type="hidden" name="id">');d.append('<button class="btn">Submit</button>')}function g(j){var p=
$("<tr>");$.each(j,function(k,i){typeof i!=="function"&&k!="id"&&k!=""&&p.append("<td>"+w[k].f(i))});p.append($('<td class="b">&#9998;</td>').click(function(){c();$.each(j,function(k,i){typeof i!=="function"&&$(':input[name="'+k+'"]',d).val(i)})}));p.append($('<td class="b">x</td>').click(function(){j.r();location.reload(true)}));m.append(p)}var f=$("<div>"),d=$("<form>"),l=$("<tr>"),m=$('<table class="l" border="1">').append(l),h=$('<a class="add btn">Add New</a>'),r=b;h.click(c);this.elem=f.append(h).append(m);
e(true);f=n.i(a);for(h=0;h<f.length;h++)g(f[h])}function q(a,b){var c=$('<div class="page s">');c.append('<h1 class="s">'+a+"</h1>");c.attr("id",a);b&&c.append(b.elem);this.c=$('<li class="s" id="'+a+'_nav">'+a+"</li>");this.e=c;this.c.click(function(){$("#nav .act").removeClass("act");$(this).addClass("act");$(".page").hide();c.show();y.attr("class","");y.addClass(a);window.location.hash=a});q.c.append(this.c);q.e.append(this.e)}function E(a){for(var b=[],c=n.i("bill"),e=0;e<c.length;e++){var g=
c[e],f=new Date(g.startTime);if(a>=f)switch(g.timeFrame){case x.n:!((a-f)/6048E5%1)&&a>=f&&b.push(g);break;case x.l:!((a-f)/12096E5%1)&&a>=f&&b.push(g);break;case x.m:if(a.getDate()==f.getDate()||f.getDate()>o.h[a.getMonth()]&&a.getDate()==o.h[a.getMonth()])b.push(g);break}}return b}function D(a){a.addClass("h s");var b=$('<div class="o">');$("body").append(b);$("#c").append(a);a.fadeIn();b.fadeIn();b.click(function(){b.remove();a.remove();$(".z").remove()})}function F(a){return a}function I(){var a=
"",b="",c=0,e="";$.each(n.i("category"),function(f,d){var l=0;a+=d.name+"|";for(var m=1;m<=12;m++){var h;h=m;for(var r=d.id,j=o.h[h-1],p=0,k=0,i=1;i<=j;i++){var s=E(new Date("2010/"+h+"/"+i));k+=s.length;for(var u=0;u<s.length;u++){var v=s[u];if(v.category==r)p+=parseInt(v.amount,10)}}h=p;b+=h+",";if(h>l)l=h}c+=l;b=b.substr(0,b.length-1)+"|";e+=Math.floor(Math.random()*16777215).toString(16)+","});var g="http://chart.apis.google.com/chart?chxl=0:|"+o.g.join("|")+"&chxr=0,0,11|1,0,"+c+"&chxt=x,y&chbh=a&chs=620x420&cht=bvs&chco="+
e.substr(0,e.length-1)+"&chds=0,"+c+",0,"+c+"&chd=t:"+b.substr(0,b.length-1)+"&chdl="+a.substr(0,a.length-1)+"&chtt=Expenses+2010";return $("<img>").attr("src",g)}function G(){var a=window.location.hash;if(a=="")a="#Overview";$(a+"_nav",q.c).click()}var y=$("body");o.q=["S","M","T","W","T","F","S"];o.g=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];o.h=[31,28,31,30,31,30,31,31,30,31,30,31];function n(a){this.d=function(){return a}}n.prototype.save=function(){if(this.id===
undefined||this.id=="")this.id=this.s();localStorage[this.d()+this.id]=JSON.stringify(this);location.reload(true)};n.prototype.load=function(a){var b=this;$.each(JSON.parse(localStorage[this.d()+a]),function(c,e){b[c]=e})};n.prototype.s=function(){var a=n.k(this.d()),b=a[a.length-1];if(b===undefined)b=-1;b++;a.push(b);localStorage[this.d()+"_i"]=JSON.stringify(a);return b};n.k=function(a){a=localStorage[a+"_i"];if(a===undefined||a===null)return[];return JSON.parse(a)};n.i=function(a){var b=[];$.each(n.k(a),
function(c,e){var g=new n(a);g.load(e);b.push(g)});return b};n.prototype.r=function(){var a=this.id,b=jQuery.grep(n.k(this.d()),function(c){return c!=a});localStorage[this.d()+"_i"]=JSON.stringify(b)};var x={n:"Weekly",l:"Fortnightly",m:"Monthly"},w={name:{a:function(){return $('<input name="name">')},name:"name",f:F},category:{a:function(){for(var a=n.i("category"),b=$('<select name="category">'),c=0;c<a.length;c++){var e=a[c];b.append('<option value="'+e.id+'">'+e.name)}return b},name:"category",
f:function(a){var b=new n("category");b.load(a);return b.name}},amount:{a:function(){return $('<input name="amount">')},name:"amount",f:function(a){return"$"+a}},timeFrame:{a:function(){return $('<select name="timeFrame"><option>'+x.n+"</option><option>"+x.l+"</option><option>"+x.m+"</option>")},name:"time_Frame",f:F},startTime:{a:function(){var a=$('<input name="startTime">'),b=new o(null,null,function(c){$("td",c.a).click(function(){var e=$("a",this).html();e!=""&&a.val(e+" "+$("caption",c.a).html());
c.a.hide()})});b.a.addClass("z");a.click(function(){var c=a.offset();y.append(b.a);b.a.css({position:"absolute",top:c.top+25,left:c.left});b.a.slideDown()});return a},name:"start_Time",f:function(a){a=new Date(a);return a.getDate()+" "+o.g[a.getMonth()]+" "+a.getFullYear()}}},H={p:new C("category",[w.name]),o:new C("bill",[w.name,w.category,w.timeFrame,w.startTime,w.amount])};q.c=$('<ul id="nav">');q.e=$('<div id="c">');y.append(q.e);y.append('<div id="l"><div /><span>Bilzy</span></div>');q.e.append(q.c);
new q("Overview",{elem:function(){return(new o(null,null,function(a){$("caption",a.a).html();$("td a",a.a).each(function(b,c){c=$(c);for(var e=c.data("date"),g=E(e),f=0,d=$("<div>"),l=0;l<g.length;l++){var m=g[l];f+=parseInt(m.amount,10);d.append(m.name+" - $"+m.amount+"<br>")}g="<br>&nbsp;";if(f>0)g="<br>$"+f;c.append(g);c.click(function(){d.prepend("<h2>"+e.getDate()+" "+o.g[e.getMonth()]+" "+e.getFullYear()+"</h2>");new D(d)})})})).a}()});new q("Categories",H.p);new q("Bills",H.o);new q("Reports",
{elem:function(){var a=$("<div>");a.append(I());return a}()});window.t=G;G()});